# Generated by Django 5.2.1 on 2025-05-08 14:14

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('ad_url', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'APARTMENT'), ('OTHER', 'OTHER')], default=api.utils.PropertyTypes['OTHER'], max_length=255)),
                ('dept_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('insee_code', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('blur_radius', models.IntegerField(blank=True, null=True)),
                ('marketing_type', models.CharField(choices=[('LIFE_ANNUITY', 'LIFE_ANNUITY'), ('SALE', 'SALE')], max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('condominium_expenses', models.FloatField(blank=True, null=True)),
                ('caretaker', models.BooleanField(blank=True, null=True)),
                ('heating_mode', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('COLLECTIVE', 'COLLECTIVE')], max_length=255)),
                ('water_heating_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('elevator', models.BooleanField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floor_count', models.IntegerField(blank=True, null=True)),
                ('lot_count', models.IntegerField(blank=True, null=True)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, choices=[('RECENT', 'RECENT')], max_length=255, null=True)),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('parking_count', models.IntegerField(blank=True, null=True)),
                ('terrace', models.BooleanField(blank=True, null=True)),
                ('terrace_surface', models.FloatField(blank=True, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, null=True)),
                ('garden', models.BooleanField(blank=True, null=True)),
                ('standing', models.BooleanField(blank=True, null=True)),
                ('new_build', models.BooleanField(blank=True, null=True)),
                ('small_building', models.BooleanField(blank=True, null=True)),
                ('corner_building', models.BooleanField(blank=True, null=True)),
                ('publication_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dealer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('energy_classification', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
